name: NASA Project CI
on:
  push:
    braches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs_on: windows-latest
    steps:
      - run: npm install
      - run: npm run build --prefix frontend
